export const expenseCategories = [
  { id: 1, title: 'Food', icon: 'food', color: '#7AA874' },
  { id: 2, title: 'Bills', icon: 'cash-100', color: '#FFA07A' },
  { id: 3, title: 'Water', icon: 'water', color: '#00BFFF' },
  {
    id: 4,
    title: 'Electricity',
    icon: 'home-lightning-bolt-outline',
    color: '#FFD700',
  },
  { id: 5, title: 'Shopping', icon: 'shopping', color: '#FFA500' },
  { id: 6, title: 'Entertainment', icon: 'youtube-tv', color: '#FF69B4' },
  { id: 7, title: 'Cable', icon: 'satellite-uplink', color: '#8B008B' },
  { id: 8, title: 'Mobile Prepaid', icon: 'cellphone', color: '#FFC0CB' },
  { id: 9, title: 'Mobile Postpaid', icon: 'cellphone-text', color: '#7B68EE' },
  { id: 10, title: 'Medical', icon: 'pill', color: '#FF6347' },
  { id: 11, title: 'Education', icon: 'school-outline', color: '#00CED1' },
  { id: 12, title: 'Food Delivery', icon: 'moped', color: '#8FBC8F' },
  { id: 13, title: 'Groceries', icon: 'basket', color: '#32CD32' },
  { id: 14, title: 'Internet', icon: 'web', color: '#ADD8E6' },
  { id: 15, title: 'Car', icon: 'car', color: '#B0C4DE' },
  { id: 16, title: 'Gas', icon: 'gas-station', color: '#DAA520' },
  {
    id: 17,
    title: 'Online Shopping',
    icon: 'shopping-search',
    color: '#87CEFA',
  },
  { id: 18, title: 'Transportation', icon: 'train-car', color: '#FF4500' },
  { id: 19, title: 'Baby Stuff', icon: 'baby-bottle', color: '#D864A9' },
  { id: 20, title: 'Insurance', icon: 'file-sign', color: '#9400D3' },
  { id: 21, title: 'E-wallet', icon: 'wallet', color: '#2E8B57' },
  { id: 22, title: 'MP2', icon: 'home-group', color: '#FF1493' },
  { id: 23, title: 'Gift', icon: 'gift', color: '#B71375' },
  { id: 24, title: 'Rent', icon: 'home-city', color: '#1A5F7A' },
  { id: 25, title: 'Loans', icon: 'cash-minus', color: '#FF8C00' },
  { id: 26, title: 'Business Expense', icon: 'store-remove', color: '#DC143C' },
  { id: 27, title: 'Supplies', icon: 'warehouse', color: '#F4A460' },
  { id: 28, title: 'Staff Salary', icon: 'account-tie', color: '#4B0082' },
  { id: 29, title: 'Others', icon: 'dots-horizontal', color: '#A9A9A9' },
];

export const incomeCategories = [
  {
    id: 1,
    title: 'Employment income',
    icon: 'briefcase-outline',
    color: '#006400',
  },
  { id: 2, title: 'Saving', icon: 'piggy-bank-outline', color: '#228B22' },
  { id: 3, title: 'Investment income', icon: 'trending-up', color: '#006400' },
  { id: 4, title: 'Rental income', icon: 'home-outline', color: '#B0C4DE' },
  { id: 5, title: 'Retirement income', icon: 'bank-outline', color: '#1E90FF' },
  { id: 6, title: 'Government benefits', icon: 'calculator', color: '#8B0000' },
  { id: 7, title: 'Other sources', icon: 'wallet-outline', color: '#2E8B57' },
];
