export const expenseCategories = [
  { id: 1, title: 'Food', icon: 'food' },
  { id: 2, title: 'Bills', icon: 'cash-100' },
  { id: 3, title: 'Water (Utility Bills)', icon: 'water' },
  {
    id: 4,
    title: 'Electricity (Utility Bills)',
    icon: 'home-lightning-bolt-outline',
  },
  { id: 5, title: 'Shopping', icon: 'shopping' },
  { id: 6, title: 'Entertainment', icon: 'youtube-tv' },
  { id: 7, title: 'Cable', icon: 'satellite-uplink' },
  { id: 8, title: 'Mobile Prepaid', icon: 'cellphone' },
  { id: 9, title: 'Mobile Postpaid', icon: 'cellphone-text' },
  { id: 10, title: 'Medical', icon: 'pill' },
  { id: 11, title: 'Education', icon: 'school-outline' },
  { id: 12, title: 'Food Delivery', icon: 'moped' },
  { id: 13, title: 'Groceries', icon: 'basket' },
  { id: 14, title: 'Internet', icon: 'web' },
  { id: 15, title: 'Car', icon: 'car' },
  { id: 16, title: 'Gas', icon: 'gas-station' },
  { id: 17, title: 'Online Shopping', icon: 'shopping-search' },
  { id: 18, title: 'Transportation', icon: 'train-car' },
  { id: 19, title: 'Baby Stuff', icon: 'baby-bottle' },
  { id: 20, title: 'Cash Savings', icon: 'cash' },
  { id: 21, title: 'Insurance', icon: 'file-sign' },
  { id: 22, title: 'E-wallet', icon: 'wallet' },
  { id: 23, title: 'Investment', icon: 'chart-line' },
  { id: 24, title: 'Salary', icon: 'tie' },
  { id: 25, title: 'MP2', icon: 'home-group' },
  { id: 26, title: 'Time Deposit', icon: 'archive-clock' },
  { id: 27, title: 'Extra Income', icon: 'bow-tie' },
  { id: 28, title: 'Gift', icon: 'gift' },
  { id: 29, title: 'Rent', icon: 'home-city' },
  { id: 30, title: 'Loans', icon: 'cash-minus' },
  { id: 31, title: 'Business Expense', icon: 'store-remove' },
  { id: 32, title: 'Business Sales', icon: 'storefront' },
  { id: 33, title: 'Supplies', icon: 'warehouse' },
  { id: 34, title: 'Staff Salary', icon: 'account-tie' },
  { id: 35, title: 'Others', icon: 'dots-horizontal' },
];

export const incomeCategories = [
  { id: 1, title: 'Employment income', icon: 'briefcase-outline' },
  { id: 2, title: 'Saving', icon: 'piggy-bank-outline' },
  { id: 3, title: 'Investment income', icon: 'trending-up' },
  { id: 4, title: 'Rental income', icon: 'home-outline' },
  { id: 5, title: 'Retirement income', icon: 'bank-outline' },
  { id: 6, title: 'Government benefits', icon: 'calculator' },
  { id: 7, title: 'Other sources', icon: 'wallet-outline' },
];
